version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: junctionx_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: junctionx_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - junctionx_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: junctionx_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://user:password@mysql:3306/junctionx_db
    networks:
      - junctionx_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: junctionx_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - junctionx_network

  language_agent:
    build:
      context: ./llm_agent
      dockerfile: Dockerfile
    container_name: junctionx_language_agent
    restart: always
    ports:
      - "8001:8001"
    networks:
      - junctionx_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  mysql_data:

networks:
  junctionx_network:
    driver: bridge
