version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: junctionx_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: junctionx_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # mount code for live reload (optional)
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql_data:
